#pragma once

#undef EE_HANDS
#undef MASTER_LEFT
#undef MASTER_RIGHT
#undef TAPPING_TERM

#define MASTER_LEFT
#define MOUSEKEY_INTERAL 33
#define MOUSEKEY_MAX_SPEED 7
#define PERMISSIVE_HOLD
#define QUICK_TAP_TERM 0
#define TAPPING_TERM 400
